# Generated by Django 6.0.3 on 2026-03-23 15:03

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSalidaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionSalidaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('deposito_destino', models.ForeignKey(help_text='Depósito al que entra', on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución de Salida Provisoria',
                'verbose_name_plural': 'Devoluciones Provisorias',
            },
        ),
        migrations.CreateModel(
            name='IngresoMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arribo', models.DateField()),
                ('descripcion', models.CharField(help_text='Ej: Carga China Enero', max_length=255)),
                ('comprobante', models.CharField(blank=True, help_text='Nro de Factura o Packing List', max_length=100)),
                ('deposito', models.ForeignKey(help_text='Depósito al que llega toda la carga', on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario responsable', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso de Mercadería',
                'verbose_name_plural': 'Ingresos de Mercadería',
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucionProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.devolucionsalidaprovisoria')),
                ('item_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_item', to='inventario.itemsalidaprovisoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_general', models.CharField(help_text='Ej: Cureta Sinus', max_length=255)),
                ('general_code', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(default='Thalys', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('sub_category', models.CharField(max_length=100)),
                ('professional_area', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria')),
                ('imagen_principal', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_principal', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.CharField(help_text='Ej: Dr. Juan Pérez, o Vendedor Carlos', max_length=100)),
                ('destino', models.CharField(help_text='Ej: Curso UBA', max_length=200)),
                ('fecha_esperada_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida Provisoria',
                'verbose_name_plural': 'Salidas Provisorias',
            },
        ),
        migrations.AddField(
            model_name='itemsalidaprovisoria',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.salidaprovisoria'),
        ),
        migrations.AddField(
            model_name='devolucionsalidaprovisoria',
            name='salida_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventario.salidaprovisoria'),
        ),
        migrations.CreateModel(
            name='StockLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_codigo', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('costo_compra_lote', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
            ],
        ),
        migrations.AddField(
            model_name='itemsalidaprovisoria',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.stocklote'),
        ),
        migrations.CreateModel(
            name='BajaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad a descontar del lote')),
                ('motivo', models.CharField(choices=[('VENCIMIENTO', 'Vencimiento de producto'), ('ROTURA', 'Rotura o Daño'), ('PERDIDA', 'Pérdida o Extravío'), ('ERROR_STOCK', 'Ajuste por diferencia de inventario')], max_length=20)),
                ('observaciones', models.CharField(blank=True, help_text='Ej: Se cayó la caja en el depósito', max_length=255)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario responsable', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas', to='inventario.stocklote')),
            ],
            options={
                'verbose_name': 'Baja de Inventario',
                'verbose_name_plural': 'Bajas de Inventario',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad a transferir')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, help_text='Ej: Reposición para el salón', max_length=255)),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='inventario.deposito')),
                ('lote_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='inventario.stocklote')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario responsable', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia Interna',
                'verbose_name_plural': 'Transferencias Internas',
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variante', models.CharField(help_text='Ej: #1 Mini Extra-Flex', max_length=100)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('sub_slug', models.SlugField(help_text='Ej: 1-mini-extra-flex', max_length=150)),
                ('costo_fob', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_landed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_0_publico', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_1_estudiante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_2_reventa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_3_mayorista', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_4_intercompany', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('oferta_vence', models.DateTimeField(blank=True, null=True)),
                ('imagen_variante', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variante_principal', to=settings.FILER_IMAGE_MODEL)),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='stocklote',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventario.variante'),
        ),
        migrations.CreateModel(
            name='ItemIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_fob_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_landed_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lote_codigo', models.CharField(max_length=100)),
                ('nuevo_precio_0_publico', models.DecimalField(decimal_places=2, help_text='Precio base obligatorio', max_digits=12)),
                ('nuevo_precio_1_estudiante', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_2_reventa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_3_mayorista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_4_intercompany', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nueva_oferta_vence', models.DateTimeField(blank=True, null=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ingresomercaderia')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.variante')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Detalle de punta', max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('imagen_asset', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagenes', to=settings.FILER_IMAGE_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.variante')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_fob', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote_referencia', models.CharField(blank=True, max_length=100)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_costos', to='inventario.variante')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AjusteComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('ERROR_CARGA', 'Corrección por error de carga'), ('INFLACION', 'Ajuste por tipo de cambio / inflación'), ('ESTRATEGIA', 'Cambio de estrategia comercial'), ('COSTO_EXTRA', 'Reajuste por costos aduaneros / flete'), ('OTROS', 'Otros motivos')], max_length=20)),
                ('observaciones', models.CharField(blank=True, help_text='Ej: DHL cobró más caro el despacho', max_length=255)),
                ('costo_fob_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_0_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_costo_fob', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar en blanco si no cambia', max_digits=12, null=True)),
                ('nuevo_precio_0', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar en blanco si no cambia', max_digits=12, null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario responsable', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_comerciales', to='inventario.variante')),
            ],
            options={
                'verbose_name': 'Ajuste Comercial (Costos/Precios)',
                'verbose_name_plural': 'Ajustes Comerciales',
            },
        ),
        migrations.AlterUniqueTogether(
            name='stocklote',
            unique_together={('variante', 'deposito', 'lote_codigo')},
        ),
    ]
