# Generated by Django 6.0.3 on 2026-04-07 18:25

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
        migrations.CreateModel(
            name='ItemSalidaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Ítem de Salida Provisoria',
                'verbose_name_plural': 'Ítems de Salidas Provisorias',
            },
        ),
        migrations.CreateModel(
            name='DevolucionSalidaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retorno al Depósito',
                'verbose_name_plural': 'Retornos al Depósito (Suma Stock)',
            },
        ),
        migrations.CreateModel(
            name='IngresoMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arribo', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Pendiente de Aprobación)'), ('APROBADO', 'Aprobado (Procesado)'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('procesado', models.BooleanField(default=False, editable=False)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso de Mercadería',
                'verbose_name_plural': 'Ingresos de Mercadería',
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucionProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.devolucionsalidaprovisoria')),
                ('item_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_item', to='inventario.itemsalidaprovisoria')),
            ],
            options={
                'verbose_name': 'Ítem de Devolución',
                'verbose_name_plural': 'Ítems de Devolución',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionSalidaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('VENTA', 'Venta / Consumido por cliente'), ('PERDIDA', 'Pérdida / Rotura'), ('MUESTRA', 'Muestra Médica (Sin cargo)')], default='VENTA', max_length=20)),
                ('comprobante_venta', models.CharField(blank=True, help_text='Nro de factura o recibo si se vendió', max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación (Venta/Faltante)',
                'verbose_name_plural': 'Liquidaciones (Ventas/Faltantes)',
            },
        ),
        migrations.CreateModel(
            name='ItemLiquidacionProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_liquidada', models.PositiveIntegerField()),
                ('item_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_item', to='inventario.itemsalidaprovisoria')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.liquidacionsalidaprovisoria')),
            ],
            options={
                'verbose_name': 'Ítem Liquidado',
                'verbose_name_plural': 'Ítems Liquidados',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_general', models.CharField(help_text='Ej: Cureta Sinus', max_length=255)),
                ('general_code', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(default='Thalys', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('sub_category', models.CharField(max_length=100)),
                ('professional_area', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False, help_text='Si está marcado, el producto será visible en la página online.', verbose_name='Publicado en Web')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria')),
                ('imagen_principal', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_principal', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='SalidaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=200)),
                ('fecha_esperada_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida en Consignación',
                'verbose_name_plural': 'Salidas en Consignación',
            },
        ),
        migrations.AddField(
            model_name='liquidacionsalidaprovisoria',
            name='salida_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='inventario.salidaprovisoria'),
        ),
        migrations.AddField(
            model_name='itemsalidaprovisoria',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.salidaprovisoria'),
        ),
        migrations.AddField(
            model_name='devolucionsalidaprovisoria',
            name='salida_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventario.salidaprovisoria'),
        ),
        migrations.CreateModel(
            name='StockLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_codigo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('costo_compra_lote', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
            ],
            options={
                'verbose_name': 'Lote de Stock',
                'verbose_name_plural': 'Existencias por Lote',
            },
        ),
        migrations.AddField(
            model_name='itemsalidaprovisoria',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.stocklote'),
        ),
        migrations.CreateModel(
            name='BajaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('VENCIMIENTO', 'Vencimiento de producto'), ('ROTURA', 'Rotura o Daño'), ('PERDIDA', 'Pérdida o Extravío'), ('ERROR_STOCK', 'Ajuste por diferencia de inventario')], max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Pendiente de Aprobación)'), ('APROBADO', 'Aprobado (Procesado)'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('procesado', models.BooleanField(default=False, editable=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas', to='inventario.stocklote')),
            ],
            options={
                'verbose_name': 'Baja de Inventario',
                'verbose_name_plural': 'Bajas de Inventario',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='inventario.deposito')),
                ('lote_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='inventario.stocklote')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia Interna',
                'verbose_name_plural': 'Transferencias Internas',
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variante', models.CharField(help_text='Ej: #1 Mini Extra-Flex', max_length=100)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('sub_slug', models.SlugField(help_text='Ej: 1-mini-extra-flex', max_length=150)),
                ('costo_fob', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_landed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_0_publico', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_1_estudiante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_2_reventa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_3_mayorista', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_4_intercompany', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('oferta_vence', models.DateTimeField(blank=True, null=True)),
                ('imagen_variante', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variante_principal', to=settings.FILER_IMAGE_MODEL)),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
            },
        ),
        migrations.AddField(
            model_name='stocklote',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventario.variante'),
        ),
        migrations.CreateModel(
            name='ItemIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_fob_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_landed_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lote_codigo', models.CharField(max_length=100)),
                ('nuevo_precio_0_publico', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nuevo_precio_1_estudiante', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_2_reventa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_3_mayorista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_4_intercompany', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ingresomercaderia')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.variante')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('imagen_asset', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagenes', to=settings.FILER_IMAGE_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.variante')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Galería de Imágenes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_fob', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote_referencia', models.CharField(blank=True, max_length=100)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_costos', to='inventario.variante')),
            ],
            options={
                'verbose_name': 'Historial de Costo',
                'verbose_name_plural': 'Historial de Costos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AjusteComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('ERROR_CARGA', 'Corrección por error de carga'), ('INFLACION', 'Ajuste por tipo de cambio / inflación'), ('ESTRATEGIA', 'Cambio de estrategia comercial'), ('COSTO_EXTRA', 'Reajuste por costos aduaneros / flete'), ('OTROS', 'Otros motivos')], max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Pendiente de Aprobación)'), ('APROBADO', 'Aprobado (Procesado)'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('procesado', models.BooleanField(default=False, editable=False)),
                ('nuevo_costo_fob', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_costo_landed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_0', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo_precio_4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_fob_ant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_0_ant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_comerciales', to='inventario.variante')),
            ],
            options={
                'verbose_name': 'Ajuste Comercial',
                'verbose_name_plural': 'Ajustes Comerciales',
            },
        ),
        migrations.AddConstraint(
            model_name='stocklote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='stock_lote_cantidad_no_negativa'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklote',
            unique_together={('variante', 'deposito', 'lote_codigo')},
        ),
    ]
