# Generated by Django 6.0.3 on 2026-04-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstocklote',
            name='cantidad_vencida',
            field=models.IntegerField(default=0, verbose_name='Cantidad Vencida'),
        ),
        migrations.AddField(
            model_name='stocklote',
            name='cantidad_vencida',
            field=models.IntegerField(default=0, verbose_name='Cantidad Vencida'),
        ),
        migrations.AlterField(
            model_name='historicalstocklote',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='stocklote',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AddConstraint(
            model_name='stocklote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_vencida__gte', 0)), name='stock_lote_cantidad_vencida_no_negativa'),
        ),
    ]
