# Generated by Django 6.0.3 on 2026-03-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemingreso',
            name='nueva_oferta_vence',
        ),
        migrations.RemoveField(
            model_name='itemingreso',
            name='nuevo_precio_oferta',
        ),
    ]
