# Generated by Django 6.0.3 on 2026-03-23 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_itemingreso_nueva_oferta_vence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajustecomercial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bajainventario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='devolucionsalidaprovisoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salidaprovisoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transferenciainterna',
            options={},
        ),
        migrations.RemoveField(
            model_name='ajustecomercial',
            name='costo_fob_anterior',
        ),
        migrations.RemoveField(
            model_name='ajustecomercial',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ajustecomercial',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='ajustecomercial',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='ajustecomercial',
            name='precio_0_anterior',
        ),
        migrations.RemoveField(
            model_name='bajainventario',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='devolucionsalidaprovisoria',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='devolucionsalidaprovisoria',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='salidaprovisoria',
            name='fecha_esperada_devolucion',
        ),
        migrations.RemoveField(
            model_name='salidaprovisoria',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='transferenciainterna',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='ajustecomercial',
            name='nuevo_costo_fob',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ajustecomercial',
            name='nuevo_precio_0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ajustecomercial',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ajustecomercial',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.variante'),
        ),
        migrations.AlterField(
            model_name='bajainventario',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bajainventario',
            name='motivo',
            field=models.CharField(choices=[('ROTURA', 'Rotura'), ('VENCIMIENTO', 'Vencimiento'), ('PERDIDA', 'Pérdida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bajainventario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devolucionsalidaprovisoria',
            name='deposito_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ingresomercaderia',
            name='comprobante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ingresomercaderia',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito'),
        ),
        migrations.AlterField(
            model_name='ingresomercaderia',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingresomercaderia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemingreso',
            name='nuevo_precio_0_publico',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salidaprovisoria',
            name='destino',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salidaprovisoria',
            name='responsable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferenciainterna',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transferenciainterna',
            name='deposito_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito'),
        ),
        migrations.AlterField(
            model_name='transferenciainterna',
            name='lote_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.stocklote'),
        ),
        migrations.AlterField(
            model_name='transferenciainterna',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
