# Generated by Django 6.0.3 on 2026-03-23 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_ajustecomercial_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustecomercial',
            name='costo_fob_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='motivo',
            field=models.CharField(choices=[('ERROR_CARGA', 'Corrección por error de carga'), ('INFLACION', 'Ajuste por tipo de cambio / inflación'), ('ESTRATEGIA', 'Cambio de estrategia comercial'), ('COSTO_EXTRA', 'Reajuste por costos aduaneros / flete'), ('OTROS', 'Otros motivos')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='precio_0_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bajainventario',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devolucionsalidaprovisoria',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devolucionsalidaprovisoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidaprovisoria',
            name='fecha_esperada_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salidaprovisoria',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transferenciainterna',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ajustecomercial',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_comerciales', to='inventario.variante'),
        ),
        migrations.AlterField(
            model_name='bajainventario',
            name='motivo',
            field=models.CharField(choices=[('VENCIMIENTO', 'Vencimiento de producto'), ('ROTURA', 'Rotura o Daño'), ('PERDIDA', 'Pérdida o Extravío'), ('ERROR_STOCK', 'Ajuste por diferencia de inventario')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transferenciainterna',
            name='deposito_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='inventario.deposito'),
        ),
        migrations.AlterField(
            model_name='transferenciainterna',
            name='lote_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='inventario.stocklote'),
        ),
    ]
