# Generated by Django 6.0.3 on 2026-03-23 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_ajustecomercial_costo_fob_anterior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajustecomercial',
            options={'verbose_name': 'Ajuste Comercial', 'verbose_name_plural': 'Ajustes Comerciales'},
        ),
        migrations.AlterModelOptions(
            name='bajainventario',
            options={'verbose_name': 'Baja de Inventario', 'verbose_name_plural': 'Bajas de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='deposito',
            options={'verbose_name': 'Depósito', 'verbose_name_plural': 'Depósitos'},
        ),
        migrations.AlterModelOptions(
            name='devolucionsalidaprovisoria',
            options={'verbose_name': 'Devolución Provisoria', 'verbose_name_plural': 'Devoluciones Provisorias'},
        ),
        migrations.AlterModelOptions(
            name='historialcosto',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de Costo', 'verbose_name_plural': 'Historial de Costos'},
        ),
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['orden'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Galería de Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='itemdevolucionprovisoria',
            options={'verbose_name': 'Ítem de Devolución', 'verbose_name_plural': 'Ítems de Devolución'},
        ),
        migrations.AlterModelOptions(
            name='itemsalidaprovisoria',
            options={'verbose_name': 'Ítem de Salida Provisoria', 'verbose_name_plural': 'Ítems de Salidas Provisorias'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='salidaprovisoria',
            options={'verbose_name': 'Salida Provisoria', 'verbose_name_plural': 'Salidas Provisorias'},
        ),
        migrations.AlterModelOptions(
            name='stocklote',
            options={'verbose_name': 'Lote de Stock', 'verbose_name_plural': 'Existencias por Lote'},
        ),
        migrations.AlterModelOptions(
            name='transferenciainterna',
            options={'verbose_name': 'Transferencia Interna', 'verbose_name_plural': 'Transferencias Internas'},
        ),
        migrations.AlterModelOptions(
            name='variante',
            options={'verbose_name': 'Variante de Producto', 'verbose_name_plural': 'Variantes de Productos'},
        ),
        migrations.CreateModel(
            name='LiquidacionSalidaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('VENTA', 'Venta / Consumido por cliente'), ('PERDIDA', 'Pérdida / Rotura'), ('MUESTRA', 'Muestra Médica (Sin cargo)')], default='VENTA', max_length=20)),
                ('comprobante_venta', models.CharField(blank=True, help_text='Nro de factura o recibo si se vendió', max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('salida_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='inventario.salidaprovisoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación de Salida',
                'verbose_name_plural': 'Liquidaciones de Salidas',
            },
        ),
        migrations.CreateModel(
            name='ItemLiquidacionProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_liquidada', models.PositiveIntegerField()),
                ('item_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_item', to='inventario.itemsalidaprovisoria')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.liquidacionsalidaprovisoria')),
            ],
            options={
                'verbose_name': 'Ítem Liquidado',
                'verbose_name_plural': 'Ítems Liquidados',
            },
        ),
    ]
