# Generated by Django 6.0.3 on 2026-04-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_ajustecomercial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucionsalidaprovisoria',
            options={'verbose_name': 'Retorno al Depósito', 'verbose_name_plural': 'Retornos al Depósito (Suma Stock)'},
        ),
        migrations.AlterModelOptions(
            name='liquidacionsalidaprovisoria',
            options={'verbose_name': 'Liquidación (Venta/Faltante)', 'verbose_name_plural': 'Liquidaciones (Ventas/Faltantes)'},
        ),
        migrations.AlterModelOptions(
            name='salidaprovisoria',
            options={'verbose_name': 'Salida en Consignación', 'verbose_name_plural': 'Salidas en Consignación'},
        ),
        migrations.AddField(
            model_name='bajainventario',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (Pendiente de Aprobación)'), ('APROBADO', 'Aprobado (Procesado)'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='ingresomercaderia',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (Pendiente de Aprobación)'), ('APROBADO', 'Aprobado (Procesado)'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20),
        ),
    ]
