# Generated by Django 6.0.3 on 2026-04-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_devolucionsalidaprovisoria_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajustecomercial',
            old_name='costo_fob_anterior',
            new_name='costo_fob_ant',
        ),
        migrations.RenameField(
            model_name='ajustecomercial',
            old_name='precio_0_anterior',
            new_name='precio_0_ant',
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (Pendiente de Aprobación)'), ('APROBADO', 'Aprobado (Procesado)'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='nuevo_costo_landed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='nuevo_precio_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='nuevo_precio_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='nuevo_precio_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ajustecomercial',
            name='nuevo_precio_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
