# Generated by Django 6.0.3 on 2026-04-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_costo_fob_anterior_ajustecomercial_costo_fob_ant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustecomercial',
            name='procesado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='bajainventario',
            name='procesado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='ingresomercaderia',
            name='procesado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
