# Generated by Django 6.0.3 on 2026-04-15 16:42

import django.db.models.deletion
import filer.fields.image
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_general', models.CharField(help_text='Ej: Cureta Sinus', max_length=255)),
                ('general_code', models.CharField(db_index=True, max_length=50)),
                ('brand', models.CharField(default='Thalys', max_length=100)),
                ('slug', models.SlugField()),
                ('sub_category', models.CharField(max_length=100)),
                ('professional_area', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False, help_text='Si está marcado, el producto será visible en la página online.', verbose_name='Publicado en Web')),
                ('atributos', models.JSONField(blank=True, default=dict, help_text='Ej: {"talla": "M", "sabor": "Menta"}')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para archivar y ocultar del sistema sin borrar el historial.', verbose_name='Activo en Sistema')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.categoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imagen_principal', filer.fields.image.FilerImageField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'historical Producto',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_general', models.CharField(help_text='Ej: Cureta Sinus', max_length=255)),
                ('general_code', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(default='Thalys', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('sub_category', models.CharField(max_length=100)),
                ('professional_area', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False, help_text='Si está marcado, el producto será visible en la página online.', verbose_name='Publicado en Web')),
                ('atributos', models.JSONField(blank=True, default=dict, help_text='Ej: {"talla": "M", "sabor": "Menta"}')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para archivar y ocultar del sistema sin borrar el historial.', verbose_name='Activo en Sistema')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria')),
                ('imagen_principal', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_principal', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVariante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_variante', models.CharField(help_text='Ej: #1 Mini Extra-Flex', max_length=100)),
                ('product_code', models.CharField(db_index=True, max_length=50)),
                ('sub_slug', models.SlugField(help_text='Ej: 1-mini-extra-flex', max_length=150)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si esta variante ya no se comercializa.', verbose_name='Variante Activa')),
                ('costo_fob', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_landed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_0_publico', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_1_estudiante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_2_reventa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_3_mayorista', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_4_intercompany', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('oferta_vence', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imagen_variante', filer.fields.image.FilerImageField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.FILER_IMAGE_MODEL)),
                ('producto_padre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'historical Variante de Producto',
                'verbose_name_plural': 'historical Variantes de Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variante', models.CharField(help_text='Ej: #1 Mini Extra-Flex', max_length=100)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('sub_slug', models.SlugField(help_text='Ej: 1-mini-extra-flex', max_length=150)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si esta variante ya no se comercializa.', verbose_name='Variante Activa')),
                ('costo_fob', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_landed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_0_publico', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_1_estudiante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_2_reventa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_3_mayorista', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_4_intercompany', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('oferta_vence', models.DateTimeField(blank=True, null=True)),
                ('imagen_variante', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variante_principal', to=settings.FILER_IMAGE_MODEL)),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'unique_together': {('producto_padre', 'sub_slug')},
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('imagen_asset', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagenes', to=settings.FILER_IMAGE_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.variante')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Galería de Imágenes',
                'ordering': ['orden'],
            },
        ),
    ]
